# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170726_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='associateddiseases',
            field=models.ManyToManyField(to='app.Disease'),
        ),
    ]
